export { default as background_leaders } from './Background_leaders.svg';
export { default as background_preview } from './Background_preview.svg';
export { default as background_authorize } from './background_authorize.svg';
export { default as background_minigame } from './Background_minigame.svg';
export { default as background_profile } from './Background_profile.svg';
export { default as background_profile_settings } from './Background_profile_settings.svg';
export { default as background_solar_system } from './background_solar_system.svg';
export { default as background_settings } from './background_settings.svg';
export { default as background_personal_account } from './background_personalAccount.svg';
