export {default as mars} from './mars.svg';
export {default as earth} from './earth.svg';
export {default as jupiter} from './jupiter.svg';
export {default as mercury} from './mercury.svg';
export {default as moon} from './moon.svg';
export {default as neptune} from './neptune.svg';
export {default as pluto} from './pluto.svg';
export {default as saturn} from './saturn.svg';
export {default as Sun} from './Sun.svg';
export {default as uranus} from './uranus.svg';
export {default as venus} from './venus.svg';

export {default as logo} from './Logo.svg';
export {default as avatar} from './Avatars.svg';
export {default as coinLogo} from './coinLogo.svg';
export {default as cupOne} from './cupOne.svg';
export {default as cupTwo} from './cupTwo.svg';
export {default as cupThree} from './cupThree.svg';
export {default as unknow_planet} from './unknow_planet.svg';
export {default as close} from './close.svg'
export {default as IconsTelegram} from './Telegram.svg'
export {default as IconsGithub} from './Github.svg'
export {default as IconsDribbble} from './Dribbble.svg'
export {default as spaceX} from './SpaceX.svg'
export {default as circle} from './circle.svg'
export {default as profile_icon} from './profile_icon.svg'
export {default as settings_header_icon} from './settings_header_icon.svg'
export {default as exit_icon} from './exit_icon.svg'